### PR TITLE
Add gsutil command to download nq dataset

### PR DESCRIPTION
**Pull request by goodhamgupta**
Hi Team,

Thanks for making this notebook. While I was trying it out on colab, I noticed that the notebook breaks on the cell that generates TSV files for the NQ dataset. The error is as follows:

error

I had added a cell to download the dataset using gsutil to the `data` folder. The command is available [here](https://ai.google.com/research/NaturalQuestions/download). 

This fixes the error and generates the TSV files as expected.

### CODE REVIEW

**Comment by goodhamgupta** [comment]
@googlebot I signed it!

**Comment by craffel** [comment]
Hi, that error is not complaining because it can't find the NQ jsonl (it should be readable from GCS, it's complaining because `data/` doesn't exist so it can't write to `data/nq-train.tsv`. You should enter a GCS path for BASE_DIR and then it won't try to write to data/ locally. Please open an issue if this doesn't work.

**Comment by craffel** [comment]
This commit should prevent this: https://github.com/google-research/text-to-text-transfer-transformer/commit/d21350e1699889d793f992a48c8bc33575435589

**Comment by goodhamgupta** [comment]
Thanks for the clarification @craffel. It works as expected after specifying the BASE_DIR.

**Pull request closed without merging**
